version: '3.3'

services:
  mockup:
    image: jordimartin/mmock
    ports:
      - 8082:8082
      - 8083:8083
    volumes:
      - type: bind
        source: "./tests/mockup/config"
        target: "/config"
        consistency: cached
  test:
    depends_on:
      - mockup
    image: registry.gitlab.com/eappointment/php-base:7.3-dev
    volumes:
      - type: bind
        source: "."
        target: "/app"
        consistency: cached
    environment:
      ZMS_API_URL: http://mockup:8083/
    working_dir: /app
    command:
      - "bash"
      - "-c"
      #- "while true;do sleep 5; date; done;"
      - sleep 10 && bin/test || while true;do sleep 5; date; done;
