swagger: '2.0'
info:
  version: 1.0.0
  title: ZMS Neo API
  description: Access to the backend function of the time management system called ZMS
  termsOfService: 'http://service.berlin.de/terminvereinbarung/'
  contact:
    name: Mathias Fischer
    email: mathias.fischer@berlinonline.de
    url: 'http://www.berlinonline.net/unternehmen/team/'
  license:
    name: Commercial
    url: 'http://www.berlinonline.net'
basePath: /terminvereinbarung/api/2
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  $ref: "routes.json"
definitions:
  appointment:
    $ref: "schema/appointment.json"
  appointmenttypes:
    $ref: "schema/appointmenttypes.json"
  availability:
    $ref: "schema/availability.json"
  calendar:
    $ref: "schema/calendar.json"
  client:
    $ref: "schema/client.json"
  cluster:
    $ref: "schema/cluster.json"
  contact:
    $ref: "schema/contact.json"
  day:
    $ref: "schema/day.json"
  department:
    $ref: "schema/department.json"
  dayoff:
    $ref: "schema/dayoff.json"
  mail:
    $ref: "schema/mail.json"
  metaresult:
    $ref: "schema/metaresult.json"
  notification:
    $ref: "schema/notification.json"
  organisation:
    $ref: "schema/organisation.json"
  owner:
    $ref: "schema/owner.json"
  process:
    $ref: "schema/process.json"
  provider:
    $ref: "schema/provider.json"
  queue:
    $ref: "schema/queue.json"
  request:
    $ref: "schema/request.json"
  scope:
    $ref: "schema/scope.json"
  status:
    $ref: "schema/status.json"
  ticketprinter:
    $ref: "schema/ticketprinter.json"
  useraccount:
    $ref: "schema/useraccount.json"
  workstation:
    $ref: "schema/workstation.json"
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
