swagger: '2.0'
info:
  version: 2.17.0
  title: ZMS (human waiting queue management) API
  x-logo:
    url: "/terminvereinbarung/api/2/doc/logo.png"
  description: |
      The ZMS system is intended to manage human waiting queues. It has the following features:

       * make appointments via a calender and initiate a process to manage an appointment
       * import requests (services) and providers (locations) from external sources
       * manage scopes for appointments, including a four level hierarchy of owner->organisation->department->scope
       * manage opening hours including closed days
       * login-system with different access levels
       * pickup for documents
       * ticketprinter support for customers without appointments (authenticated, lockable, timeable)
       * calldisplay support
       * collecting statistics like waiting time or served clients per day
       
       This documentation covers the API-level access to these features.
  termsOfService: 'http://service.berlin.de/terminvereinbarung/'
  contact:
    name: Mathias Fischer
    email: mathias.fischer@berlinonline.de
    url: 'http://www.berlinonline.net/unternehmen/team/'
  license:
    name: Commercial
    url: 'http://www.berlinonline.net'
basePath: /terminvereinbarung/api/2
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  httpauth:
    type: basic
    description: |
        The API uses two variants of authentication. An application can use basic authentication via HTTP for identification. As an alternative, there is a header with the name "X-Authkey". This key can be optained by accessing "/workstation/login/".

        According to the application settings, there might be different rights to use API methods. Further rights depend on the settings for the authorized useraccount.
security:
    - httpauth: []
paths:
  $ref: "routes.json"
definitions:
  apikey:
    $ref: "schema/apikey.json"
  appointment:
    $ref: "schema/appointment.json"
  availability:
    $ref: "schema/availability.json"
  calendar:
    $ref: "schema/calendar.json"
  calldisplay:
    $ref: "schema/calldisplay.json"
  client:
    $ref: "schema/client.json"
  cluster:
    $ref: "schema/cluster.json"
  config:
    $ref: "schema/config.json"
  contact:
    $ref: "schema/contact.json"
  day:
    $ref: "schema/day.json"
  department:
    $ref: "schema/department.json"
  dayoff:
    $ref: "schema/dayoff.json"
  exchange:
    $ref: "schema/exchange.json"
  log:
    $ref: "schema/log.json"
  mail:
    $ref: "schema/mail.json"
  mimepart:
    $ref: "schema/mimepart.json"
  metaresult:
    $ref: "schema/metaresult.json"
  notification:
    $ref: "schema/notification.json"
  organisation:
    $ref: "schema/organisation.json"
  owner:
    $ref: "schema/owner.json"
  process:
    $ref: "schema/process.json"
  provider:
    $ref: "schema/provider.json"
  queue:
    $ref: "schema/queue.json"
  request:
    $ref: "schema/request.json"
  scope:
    $ref: "schema/scope.json"
  session:
    $ref: "schema/session.json"
  slot:
    $ref: "schema/slot.json"
  status:
    $ref: "schema/status.json"
  ticketprinter:
    $ref: "schema/ticketprinter.json"
  useraccount:
    $ref: "schema/useraccount.json"
  workstation:
    $ref: "schema/workstation.json"
