swagger: '2.0'
info:
  version: 1.0.0
  title: ZMS Neo API
  description: Access to the backend function of the time management system called ZMS
  termsOfService: 'http://service.berlin.de/terminvereinbarung/'
  contact:
    name: Mathias Fischer
    email: mathias.fischer@berlinonline.de
    url: 'http://www.berlinonline.net/unternehmen/team/'
  license:
    name: Commercial
    url: 'http://www.berlinonline.net'
basePath: /terminvereinbarung/api/2
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  httpauth:
    type: basic
    description: 'The API uses two systems of authentication. An application uses basic authentication via HTTP to identify. According to the application settings, there might be different rights to use API methods. The user managment via the entity "useraccount" works with the Header "X-Authkey". With the methods in the path "/workstation", a valid "X-Authkey" is generated. Further rights depend on the settings for the authorized useraccount.'
security:
    - httpauth: []
paths:
  $ref: "routes.json"
definitions:
  appointment:
    $ref: "schema/appointment.json"
  availability:
    $ref: "schema/availability.json"
  calendar:
    $ref: "schema/calendar.json"
  calldisplay:
    $ref: "schema/calldisplay.json"
  client:
    $ref: "schema/client.json"
  cluster:
    $ref: "schema/cluster.json"
  config:
    $ref: "schema/config.json"
  contact:
    $ref: "schema/contact.json"
  day:
    $ref: "schema/day.json"
  department:
    $ref: "schema/department.json"
  dayoff:
    $ref: "schema/dayoff.json"
  log:
    $ref: "schema/log.json"
  mail:
    $ref: "schema/mail.json"
  mimemart:
    $ref: "schema/mimepart.json"
  metaresult:
    $ref: "schema/metaresult.json"
  notification:
    $ref: "schema/notification.json"
  organisation:
    $ref: "schema/organisation.json"
  owner:
    $ref: "schema/owner.json"
  process:
    $ref: "schema/process.json"
  provider:
    $ref: "schema/provider.json"
  queue:
    $ref: "schema/queue.json"
  request:
    $ref: "schema/request.json"
  scope:
    $ref: "schema/scope.json"
  session:
    $ref: "schema/session.json"
  slot:
    $ref: "schema/slot.json"
  status:
    $ref: "schema/status.json"
  ticketprinter:
    $ref: "schema/ticketprinter.json"
  useraccount:
    $ref: "schema/useraccount.json"
  workstation:
    $ref: "schema/workstation.json"
