# Workflow for deploying both PHP and Node.js projects to GitHub Pages
name: Deploy PHP and Node.js static content to Pages

on:
  # Runs on pushes targeting the default branch (main)
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Specify PHP version as per your requirement
          extensions: mbstring, json
          tools: composer

      # Step 3: Install PHP dependencies for both projects (zmsapi and zmscitizenapi)
      - name: Install PHP dependencies
        run: |
          composer install --working-dir=zmsapi
          composer install --working-dir=zmscitizenapi

      # Step 4: Run PHP scripts for both projects
      - name: Run PHP scripts
        run: |
          cd zmsapi && composer run-script post-install-cmd && cd ..
          cd zmscitizenapi && composer run-script post-install-cmd && cd ..

      # Step 5: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify Node.js version as needed

      # Step 6: Install Node.js dependencies for zmsapi
      - name: Install Node.js dependencies for zmsapi
        run: |
          cd zmsapi
          npm install

      # Step 7: Build and generate Swagger documentation for zmsapi
      - name: Build and document zmsapi
        run: |
          cd zmsapi
          npm run doc

      # Step 8: Install Node.js dependencies for zmscitizenapi
      - name: Install Node.js dependencies for zmscitizenapi
        run: |
          cd zmscitizenapi
          npm install

      # Step 9: Build and generate Swagger documentation for zmscitizenapi
      - name: Build and document zmscitizenapi
        run: |
          cd zmscitizenapi
          npm run doc

      # Step 10: Set up GitHub Pages for deployment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 11: Upload the static content to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Upload the entire repository, including the generated docs

      # Step 12: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
