name: unit tests

on:
  workflow_call:

jobs:
  module-test:
    runs-on: ubuntu-latest
    container:
      image: "registry.gitlab.com/eappointment/php-base:${{ matrix.php_version }}-dev"
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
      - name: Install Composer Dependencies
        run: |
          cd "${{ matrix.module }}"
          composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Run Unit Tests
        run: |
          cd "${{ matrix.module }}"
          ./vendor/bin/phpunit
    strategy:
      matrix:
        include:
          - module: zmsadmin
            php_version: "8.0"
          - module: zmscalldisplay
            php_version: "8.0"
          - module: zmsdldb
            php_version: "8.0"
          - module: zmsentities
            php_version: "8.0"
          - module: zmsmessaging
            php_version: "8.0"
          - module: zmsslim
            php_version: "8.0"
          - module: zmsstatistic
            php_version: "8.0"
